version: '4.18'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgis/postgis
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432
    restart: on-failure

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    env_file:
      - .env
    ports:
      - 6379:6379
    restart: on-failure

  mediamtx:
    image: aler9/rtsp-simple-server
    volumes:
      - ./dev/mediamtx/mediamtx.yml:/mediamtx.yml
    ports:
      - 8554:8554
      - 8888:8888
      - 9997:9997
    restart: on-failure

volumes:
  postgres_data:
  redis_data:
