version: '4.18'

services:
  web:
    build: .
    ports:
      - 8501:8501
    command:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: map
      ALLOW_IP_RANGE: 0.0.0.0
    ports:
      - 5432:5432
