# Generated by Django 4.2 on 2023-05-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_is_staff_customuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='source',
            field=models.CharField(default='', max_length=255),
        ),
    ]
