# Generated by Django 4.2 on 2023-04-30 22:39

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT(0.0 0.0)', srid=4326),
        ),
    ]
