# Generated by Django 4.2 on 2023-05-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_customuser_livestreams_livestream_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='livestreams',
            field=models.ManyToManyField(related_name='users', to='dashboard.livestream'),
        ),
    ]
