# Generated by Django 4.2 on 2023-05-09 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_customuser_livestreams'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('time_created', models.TimeField(auto_now_add=True)),
                ('livestreams', models.ManyToManyField(related_name='viewports', to='dashboard.livestream')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
