# Generated by Django 4.2 on 2023-05-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_viewport'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewport',
            name='name',
            field=models.CharField(default='Viewport', max_length=255),
        ),
    ]
