# Generated by Django 4.2 on 2023-05-23 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_remove_livestream_agency_remove_livestream_hls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='latest_frame',
            field=models.ImageField(blank=True, null=True, upload_to='frames'),
        ),
    ]
