# Generated by Django 4.2 on 2023-05-24 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dashboard', '0016_alter_livestream_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestream',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='livestreams', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='livestream',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
