# Generated by Django 4.2 on 2023-05-24 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dashboard', '0017_alter_livestream_groups_alter_livestream_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='group_memberships', to='auth.group'),
        ),
        migrations.DeleteModel(
            name='Agency',
        ),
    ]
