# Generated by Django 4.2 on 2023-05-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_remove_customuser_user_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestream',
            name='type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
