# Generated by Django 4.2 on 2023-05-31 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_livestream_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='is_live',
            field=models.BooleanField(default=True),
        ),
    ]
